-- MySQL Script generated by MySQL Workbench
-- Sun Nov 22 18:50:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Zvezdnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zvezdnik` (
  `idZvezdnik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `letoRojstva` YEAR NOT NULL,
  `letoSmrti` YEAR NULL,
  PRIMARY KEY (`idZvezdnik`),
  UNIQUE INDEX `Ime_UNIQUE` (`ime` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Naslov`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Naslov` (
  `idNaslov` INT NOT NULL AUTO_INCREMENT,
  `tip` VARCHAR(10) NOT NULL,
  `glavniNaslov` VARCHAR(45) NOT NULL,
  `prvotniNaslov` VARCHAR(45) NOT NULL,
  `zaOdrasle` TINYINT(1) NOT NULL,
  `zacetnoLeto` YEAR NOT NULL,
  `letoKonca` YEAR NULL,
  `dolzinaMinute` INT NOT NULL,
  `povprecnaOcena` FLOAT NULL,
  `steviloGlasov` INT NOT NULL,
  PRIMARY KEY (`idNaslov`),
  UNIQUE INDEX `glavniNaslov_UNIQUE` (`glavniNaslov` ASC),
  UNIQUE INDEX `prvotniNaslov_UNIQUE` (`prvotniNaslov` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Žanr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Žanr` (
  `idZanr` INT NOT NULL AUTO_INCREMENT,
  `imeZanra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idZanr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DrugiNaslov`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DrugiNaslov` (
  `idDrugiNaslov` INT NOT NULL AUTO_INCREMENT,
  `naslovRegija` VARCHAR(45) NOT NULL,
  `regija` VARCHAR(45) NOT NULL,
  `jezik` VARCHAR(45) NULL,
  `jePrvotni` TINYINT(1) NOT NULL,
  `idNaslov` INT NOT NULL,
  PRIMARY KEY (`idDrugiNaslov`, `idNaslov`),
  INDEX `fk_AKA_Film1_idx` (`idNaslov` ASC),
  CONSTRAINT `fk_AKA_Film1`
    FOREIGN KEY (`idNaslov`)
    REFERENCES `Naslov` (`idNaslov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Vloga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vloga` (
  `idVloga` INT NOT NULL AUTO_INCREMENT,
  `idZvezdnik` INT NOT NULL,
  `idNaslov` INT NOT NULL,
  `kategorija` VARCHAR(45) NOT NULL,
  `zaposlitev` VARCHAR(45) NULL,
  `igranaOseba` VARCHAR(45) NULL,
  PRIMARY KEY (`idVloga`, `idZvezdnik`, `idNaslov`),
  INDEX `fk_Zvezdnik_has_Film_Film1_idx` (`idNaslov` ASC),
  INDEX `fk_Zvezdnik_has_Film_Zvezdnik1_idx` (`idZvezdnik` ASC),
  CONSTRAINT `fk_Zvezdnik_has_Film_Zvezdnik1`
    FOREIGN KEY (`idZvezdnik`)
    REFERENCES `Zvezdnik` (`idZvezdnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zvezdnik_has_Film_Film1`
    FOREIGN KEY (`idNaslov`)
    REFERENCES `Naslov` (`idNaslov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GlavnaEkipa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GlavnaEkipa` (
  `direktor` TINYINT(1) NULL,
  `pisatelj` TINYINT(1) NULL,
  `idZvezdnik` INT NOT NULL,
  `idNaslov` INT NOT NULL,
  PRIMARY KEY (`idZvezdnik`, `idNaslov`),
  INDEX `fk_GlavnaEkipa_Zvezdnik1_idx` (`idZvezdnik` ASC),
  INDEX `fk_GlavnaEkipa_Film1_idx` (`idNaslov` ASC),
  CONSTRAINT `fk_GlavnaEkipa_Zvezdnik1`
    FOREIGN KEY (`idZvezdnik`)
    REFERENCES `Zvezdnik` (`idZvezdnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GlavnaEkipa_Film1`
    FOREIGN KEY (`idNaslov`)
    REFERENCES `Naslov` (`idNaslov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Epizode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Epizode` (
  `idEpizode` INT NOT NULL AUTO_INCREMENT,
  `stSezone` VARCHAR(45) NOT NULL,
  `stEpizode` VARCHAR(45) NOT NULL,
  `idNaslov` INT NOT NULL,
  PRIMARY KEY (`idEpizode`, `idNaslov`),
  INDEX `fk_Epizode_Naslov1_idx` (`idNaslov` ASC),
  CONSTRAINT `fk_Epizode_Naslov1`
    FOREIGN KEY (`idNaslov`)
    REFERENCES `Naslov` (`idNaslov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FilmiPoŽanrih`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FilmiPoŽanrih` (
  `idZanr` INT NOT NULL,
  `idNaslov` INT NOT NULL,
  PRIMARY KEY (`idZanr`, `idNaslov`),
  INDEX `fk_Žanr_has_Naslov_Naslov1_idx` (`idNaslov` ASC),
  INDEX `fk_Žanr_has_Naslov_Žanr1_idx` (`idZanr` ASC),
  CONSTRAINT `fk_Žanr_has_Naslov_Žanr1`
    FOREIGN KEY (`idZanr`)
    REFERENCES `Žanr` (`idZanr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Žanr_has_Naslov_Naslov1`
    FOREIGN KEY (`idNaslov`)
    REFERENCES `Naslov` (`idNaslov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Uporabnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Uporabnik` (
  `idUporabnik` INT NOT NULL AUTO_INCREMENT,
  `uporabniskoIme` VARCHAR(45) NOT NULL,
  `geslo` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  PRIMARY KEY (`idUporabnik`),
  UNIQUE INDEX `uporabniskoIme_UNIQUE` (`uporabniskoIme` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ogledano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ogledano` (
  `idUporabnik` INT NOT NULL,
  `idNaslov` INT NOT NULL,
  `komentar` TEXT NULL,
  `ocena` TINYINT(10) NULL DEFAULT 0,
  PRIMARY KEY (`idUporabnik`, `idNaslov`),
  INDEX `fk_Uporabnik_has_Naslov_Naslov1_idx` (`idNaslov` ASC),
  INDEX `fk_Uporabnik_has_Naslov_Uporabnik1_idx` (`idUporabnik` ASC),
  CONSTRAINT `fk_Uporabnik_has_Naslov_Uporabnik1`
    FOREIGN KEY (`idUporabnik`)
    REFERENCES `Uporabnik` (`idUporabnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uporabnik_has_Naslov_Naslov1`
    FOREIGN KEY (`idNaslov`)
    REFERENCES `Naslov` (`idNaslov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
